README.md
docker-compose.yml

Added the docker volume in the docker-compose.yml and README.md

fix: docker volume

---

.gitea/workflows/vdirsyncer-deployment-dev.yaml
.gitea/workflows/vdirsyncer-deployment.yaml

Fixed the gitea/github actions job name.

fix: job name

---

Dockerfile
README.md
files/scripts/start.sh

Alpine 3.20.2
Python 3.12.3
Pip 24.2.0
Pipx 1.6.0

update: dependencies

---

.gitea/workflows/vdirsyncer-deployment-dev.yaml
.gitea/workflows/vdirsyncer-deployment.yaml

Added Ntfy workflow notifications

feat: workflow notifications

---

README.md

fix: version badge

---

files/scripts/start.sh

fix: rm parameter

---

Dockerfile
README.md

README.md and image version update

README.md and image version update

---

Dockerfile

fix: version tag

---

Dockerfile

fix: FROM alpine version

---

.gitea/workflows/vdirsyncer-deployment-dev.yaml
.gitea/workflows/vdirsyncer-deployment.yaml
Dockerfile
README.md
files/scripts/start.sh

Alpine to 3.21.2
Python to 3.12.8
Pip to 24.3.1
Github Actions Versions

perf: dependencies update

---

README.md
docker/files/scripts/start.sh

docs: README.md
fix: start.sh PRE_SYNC_SCRIPT_FILE

docs: README.md

---

.gitea/workflows/vdirsyncer-deployment.yaml
.github/release-drafter.yml
.github/workflows/release-drafter.yaml

ci: release drafter

---

.github/dependabot.yaml

ci: dependabot

---

.github/workflows/ci-docker-build.yaml
README.md
docker/Dockerfile

ci: docker build pipeline with dockerfile linter

ci: docker build pipeline with dockerfile linter

---

.gitea/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/config.yml

chore: config.yml

---

.gitea/workflows/vdirsyncer-deployment-dev.yaml
.gitea/workflows/vdirsyncer-deployment.yaml
.github/dependabot.yaml
.github/workflows/ci-docker-build.yaml
.github/workflows/release-drafter.yaml

ci: pipeline performance

---

docker/Dockerfile

feat: alpine:3.22.1

---

docker/Dockerfile

fix: pip versions

---

.github/workflows/lint-actions.yaml

ci: actions linter

---

.github/workflows/lint-dockerfile.yaml

ci: lint dockerfile

---

.github/workflows/lint-pull-requests.yaml

ci: pr linter

---

docker/Dockerfile

build: file command
Fixes Issues #40

build: file command

---

.gitea/workflows/vdirsyncer-deployment-dev.yaml
.gitea/workflows/vdirsyncer-deployment.yaml
.github/workflows/container-build-check.yaml
.github/workflows/gitleaks-scan.yaml
.github/workflows/lint-actions.yaml
.github/workflows/lint-dockerfile.yaml
.github/workflows/lint-shell-scripts.yaml
docker/Dockerfile

build: dynamic build date

---

.github/release-drafter.yml

ci: release drafter quay.io info

ci: release drafter quay.io info

---

.github/workflows/container-build-check.yaml
docker/Dockerfile

build: vdirsyncer 0.20.0

---

docker/Dockerfile

build: image version

---

docker/files/scripts/healthcheck.sh

feat: healthcheck script

---

docker/files/scripts/start.sh

perf: start.sh improvements

---

docker/Dockerfile
docker/files/scripts/start.sh

build: dependencies and log messages

build: dependencies and log messages

---

README.md
docker/Dockerfile
docker/docker-compose.yml
docker/files/scripts/start.sh

perf!: LOG_LEVEL renamed to SUPERCRONIC_FLAGS

perf!: LOG_LEVEL renamed to SUPERCRONIC_FLAGS
